version: "3.8"

services:
  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./product-service:/app
      - /app/node_modules
      - /app/dist
    networks:
      - product-reviews-network

networks:
  product-reviews-network:
    driver: bridge
